/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-10-02 00:14:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.trabalhoEly.cadastro;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class edit_005fjogo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Editar Jogo</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 800px; \r\n");
      out.write("            margin-top: 50px; \r\n");
      out.write("            padding: 30px; \r\n");
      out.write("            border-radius: 10px; \r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control {\r\n");
      out.write("            transition: border-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("        button.btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        button.btn:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        /* Adiciona animações */\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; }\r\n");
      out.write("            to { opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("        .form-group {\r\n");
      out.write("            animation: fadeIn 0.8s ease forwards;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>Editar Jogo</h2>\r\n");
      out.write("\r\n");
      out.write("    ");

        int id = Integer.parseInt(request.getParameter("id"));
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jogosdb", "root", "root");
        PreparedStatement ps = con.prepareStatement("SELECT * FROM jogos WHERE id=?");
        ps.setInt(1, id);
        ResultSet rs = ps.executeQuery();
        rs.next();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"edit_jogo.jsp?id=");
      out.print( id );
      out.write("\" method=\"post\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"nome\">Nome:</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"nome\" value=\"");
      out.print( rs.getString("nome") );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"plataforma\">Plataforma:</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"plataforma\" value=\"");
      out.print( rs.getString("plataforma") );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"genero\">Gênero:</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"genero\" value=\"");
      out.print( rs.getString("genero") );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"ano_lancamento\">Ano de Lançamento:</label>\r\n");
      out.write("            <input type=\"number\" class=\"form-control\" name=\"ano_lancamento\" value=\"");
      out.print( rs.getInt("ano_lancamento") );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-warning\">Atualizar</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    ");

        if (request.getMethod().equalsIgnoreCase("POST")) {
            String nome = request.getParameter("nome");
            String plataforma = request.getParameter("plataforma");
            String genero = request.getParameter("genero");
            int anoLancamento = Integer.parseInt(request.getParameter("ano_lancamento"));

            PreparedStatement psUpdate = con.prepareStatement("UPDATE jogos SET nome=?, plataforma=?, genero=?, ano_lancamento=? WHERE id=?");
            psUpdate.setString(1, nome);
            psUpdate.setString(2, plataforma);
            psUpdate.setString(3, genero);
            psUpdate.setInt(4, anoLancamento);
            psUpdate.setInt(5, id);
            psUpdate.executeUpdate();

            con.close();
            response.sendRedirect("index.jsp");
        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
